version: '3.8'

services:
  h2-database:
    image: oscarfonts/h2
    container_name: coindesk-h2
    ports:
      - "8082:8082"  # H2 Console port
      - "9092:9092"  # TCP port for database connection
    environment:
      - H2_OPTIONS=-ifNotExists
      - JAVA_OPTS=-Dh2.bindAddress=0.0.0.0
